export const siteConfig = {
  name: "Desert Storm Adventure",
  shortName: "Desert Storm",
  description:
    "Premium desert adventures in the dunes — quad biking, dune buggies, camel rides, sandboarding and sunset safaris. Book your slot, slide to confirm, ride.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://desertstormadventure.com",
  locale: "en_AE",
  currency: "AED",
  // Default social card is generated by app/opengraph-image.tsx.
  contact: {
    phone: "+971 50 000 0000",
    email: "rides@desertstormadventure.com",
    whatsapp: "+971500000000",
  },
  social: {
    instagram: "https://instagram.com/desertstormadventure",
    tiktok: "https://tiktok.com/@desertstormadventure",
    youtube: "https://youtube.com/@desertstormadventure",
  },
} as const;

/** Primary navigation shown in the header. Labels chosen to fit the brand and
 *  each destination's own headline (Gallery → "Moments in the dunes", etc.). */
export const mainNav = [
  { label: "Home", href: "/" },
  { label: "Adventures", href: "/adventures" },
  { label: "Moments", href: "/gallery" },
  { label: "Our Story", href: "/about" },
  { label: "Get in Touch", href: "/contact" },
] as const;

export type Category = {
  slug: "quad" | "buggy" | "mx" | "safari" | "combo";
  name: string;
  tagline: string;
  blurb: string;
};

export const categories: Category[] = [
  {
    slug: "quad",
    name: "Quad Biking",
    tagline: "Grip the dunes",
    blurb: "Automatic & semi-auto quads from 250cc to the raptor 700 — for first-timers to throttle junkies.",
  },
  {
    slug: "buggy",
    name: "Dune Buggies",
    tagline: "Two seats, big power",
    blurb: "Can-Am Maverick & Polaris RZR side-by-sides up to 2500cc. Roll cages, harnesses, pure adrenaline.",
  },
  {
    slug: "mx",
    name: "MX / Dirt Bikes",
    tagline: "For the experienced",
    blurb: "Gas Gas, KTM, Yamaha & Honda 450s. Open desert tracks for riders who already know how to ride.",
  },
  {
    slug: "safari",
    name: "Desert Safari",
    tagline: "The classic",
    blurb: "Dune bashing, camel rides, sandboarding, sunset & BBQ camp experiences.",
  },
  {
    slug: "combo",
    name: "Combo Packages",
    tagline: "Best value",
    blurb: "Bundle a quad or buggy session with a full safari + dinner. The whole desert in one booking.",
  },
];
